### ISSUE TITLE
Can Newton VR be used with the valve lab renderer

### ISSUE THREAD

**Issue by ca396** [TomorrowTodayLabs/NewtonVR#100]
Hello all,

REALLY GREAT software you have created. I'm working on a demo piece with the vive. I love the look of the Valve lab renderer. Is it possible to use the two together. The Valve main camera seems to have a script to make the beautiful shadows. When I use the NVRplayer and delete Valves main camera no shadows. I am much more a artist than code guy. Is this approach reasonable.? Thanks for making this code available. It will help advance the artform no doubt. Also as a former Seattle person I must add "Go Seahawks"

Cheers 

Douglas Huff
Arkitek Scientific

**Comment by SmartCarrion** [comment]
I use both together for my game "Ship It" with no problem.  Well, no problem I think is caused by Newton...  You just take the NewtonVR player prefab, and add the Valve camera script to it in the right place.  Follow the lab renderer setup instructions and check out the issues and fixes on their github page.  

Make sure you put the lab renderer camera script on the game camera, not the UI camera.

**Comment by ca396** [comment]
Thanks for the info. I was able to get the scene working mostly by adding the Valve camera script to the NVRPlayer "head" just below the audio listener component. All is well until I start using the controllers then every so often I get a  short glitch in the display thru the Vive. Seems like just a frame or two out of whack.  Not happening with no controller activity or with the native Unity renderer.  So close to working !! Any suggestions would be welcome.

**Comment by SmartCarrion** [comment]
Have you applied these fixes? https://github.com/ValveSoftware/the_lab_renderer/pulls

you could check your profiler and see what is happening during that frame. Try running the game window with 'maximize on play' too.  or with the scene window covered up.  It takes a bunch of resources to render that view.

**Comment by ca396** [comment]
I will try those suggestions. Thanks so much.

**Comment by SmartCarrion** [comment]
the latest 5.5 patch release (p3) fixed another bug with Single Pass Rendering that I encountered in combination with the lab renderer.  I suggest grabbing that build of Unity if you are still having trouble.  You should probably mark this as closed unless you have an issue specifically related to NewtonVR.  i.e. can you reproduce something in the example scene?

**Comment by ca396** [comment]
Thanks for the heads up. I have been on a different project for the past few weeks and haven't been able to work on this lately. I will check out the patches as soon as possible. I will mark this as closed
