### ISSUE TITLE
Oculus Touch via SteamVR Problems

### ISSUE THREAD

**Issue by EcstaticalEcstatic** [TomorrowTodayLabs/NewtonVR#101]
Oculus Touch via SteamVR doesn't work. Objects cannot be interacted with, and the example scene functions as if it were using an unmodified steamvr.
A workaround is (Obviously) using the Oculus SDK, though it is an odd issue. The controllers don't even vibrate on collision.

**Comment by keithbradner** [comment]
That is indeed a strange issue. Are you on the latest version from github? The touch controllers are working fine for me with SteamVR and SteamVR Beta. What version of Unity are you running?

**Comment by keithbradner** [comment]
I'm going to assume this was fixed. Please comment if you're still having issues.

**Comment by EcstaticalEcstatic** [comment]
Sorry for the late response.
NewtonVR actually errors with: "Error. Unsupported device type: oculus_cv1_controller_left"
Have you got the early dev release version of touch? Just circumventing the check by defaulting to the oculus setup in NVRSteamVRInputDevice throws a bunch more errors, but they now have ghost colliders so objects can be picked up, though some functionality is still missing.

**Comment by keithbradner** [comment]
Have you updated to version 1.18? We added support for that controller a few versions ago.

**Comment by EcstaticalEcstatic** [comment]
Yeah, it's fixed now. (The attatch points are a bit wierd though, so I added a attatchpoint variable to NVRHand, and used that rather than the AttatchedHand's transform in NVRInteractableItem.cs)
