### ISSUE TITLE
Differing interactions for different Items

### ISSUE THREAD

**Issue by Theodorehip** [TomorrowTodayLabs/NewtonVR#102]
Hi team.
I've made a post about a similar problem before which was solved, now i have a different issue.
Long story short, I think it feels natural to have objects picked up by the trigger, and for the interaction method to be (Hold). But later in my project, i have an item which i would like to keep attached to the players hand but also still be intractable with. I've been trying to override certain methods within your NVRInteractable, but it seems the issue would have to stem all the way back to NVRHand. I have tried to get around this by using AutoAttach instead, and simply changing the host buttons while the object is being held so the buttons don't interfere with each other. but that begins to cause a whole slew of other problems. I know this really isn't an issue, it's more of a request for help, but it would be great if someone could help me out with implementing this.

Thank You.

**Comment by SmartCarrion** [comment]
I've been planning a similar feature...a gun/object that is attached in a certain game mode. 

I haven't started implementing it yet, but since you are just looking for ideas, I'm thinking about re-initializing the hand with a new model (the gun). Then I don't have to worry about it being dropped or anything. 

I probably want it to be quickly grabbable and will end up switching to toggle mode or creating a new interaction mode (like Gun mode). 

Let us know what you learn. I still want to publish my two handed interactions, but I've made so many little changes now it is tough to fork cleanly. I'm just not good enough at git probably!

**Comment by Theodorehip** [comment]
Like i said in my first post. I've tried many things, one being making a custom InteractorClass that implements the NVRInteractableAutoAttach and overrides the key components.

Ive tried simply stopping the EndInteraction from starting when they let go. But that led to other problems, it seems it's called from another source that cant be overriden easily, like the NVRHand.cs. 

I dont know if you're committed to this git, but i have not, and learning how it is built from the ground up is going to take more than a few days. I think that's the only way i'll be able to implement my own custom overrides on those classes without stepping on any toes.

I may try what you're doing and completely replace the player hand lol, but we'll see if it has to come to that.

I'll update if i solve the problem.

**Comment by SmartCarrion** [comment]
You definitely need to modify the hand, and it isn't as tough as you are
thinking!

**Comment by Theodorehip** [comment]
I kind of just want to do separate scripts with overrides. I don't really want to modify the main class because i still want to pull the latest updates from the repository. And i know it's probably not hard. I've been coding now in multiple languages for about 6 years now, but i'm mostly self-taught and some of the things some people take for granted knowing, kinda stump me. 

The way i learned to code is simply by brute forcing, I would sit down with a goal, and research exactly what i need to know to get to that goal alone, sure knowledge accumulates over the years, but sometimes important basic things get left out. So when i'm looking at someone else's code, seeing some syntax and/or methods/casts that seems basic to some people, i may not have the knowledge of.

**Comment by keithbradner** [comment]
Generally we've made the system with sticking to one interaction system in mind. But, it should be adaptable to your scenario and I think you're on the right track. If you inherit from NVRInteractableItemAutoAttach, and then in the BeginInteraction you set NVRPlayer.Instance.InteractionStyle to InteractionStyle.ByScript that might work out for you. Then you can control when it is attached and detached. Just set it back to hold when you're done with that item.
