### ISSUE TITLE
High frequency bouncing when forcing a collision (physics material)

### ISSUE THREAD

**Issue by victorazzo** [TomorrowTodayLabs/NewtonVR#107]
If you add bounciness to your NVR Interactable Item (say a sphere), dragging it with your controller against a static object will make it bounce with a very high frequency (probably 1/fixed time step). In these occasions, ideally the Interactable item should behave just like the objects with no bounciness in your template scene.
By the way, thanks for this great tool!

**Comment by keithbradner** [comment]
That had not occured to me but was causing issues in my own project :) Thanks for the report. I've gone ahead and fixed this in 1.17. Basically I just null out the physical materials on attach and cache them away. Then on detach I readd them back. Please reopen this if this does not fix your issue.

**Comment by victorazzo** [comment]
@zite,

Thanks for looking into this. So would this make all physics materials in compound colliders associated to a rigidbody to be null while attached? I'm wondering if these would not create an issue for an application like a table tennis paddle, where a certain friction and/or bounciness is desirable on each paddle, to interact with a ball differently...
But the feature you implemented would certainly be useful for many people. Could a better solution be adding this as another checkbox (public variable) in the NVR Interactable Item component? Something like "Disable physics materials on attach"?
Apparently I can't re-open an issue that wasn't closed by myself -  but if you think this would be better, I can re-create the issue post.

**Comment by keithbradner** [comment]
Ah, good point. I'll do that now.

**Comment by keithbradner** [comment]
Added that variable. Thanks for the quick review.
