### ISSUE TITLE
Leap Motion Orion with NewtonVR

### ISSUE THREAD

**Issue by Martichoras** [TomorrowTodayLabs/NewtonVR#11]
Hi people, I love your work!

I have a small issue I hope you might be able to help me with, even though it doesn't directly relate to HTC Vive :)
### Issue Description

I have been trying to implement NewtonVR for Leap Motion, and had the same #2  by robnewman, but solved it using his solution (i.e. initialized). I no longer have any errors, but even though pinch is registered, it doesn't pick up any objects with the `NVRInteractableItem`-script.
### Project Screenshots

You can see screenshots of the project structure and warnings [https://www.dropbox.com/sh/79vmwcocb5lfe01/AADxc4IRFSAkBbBhl_aTWWlna?dl=0](url) *

_\* Don't know why the link doesn't work, but try copy-pasting it into the browser instead._
### Quick Overview
1. The project uses the PinchDetect-package/script.
2. The `HandFollow`-script is designed to follow the position and orientation of the palm of the hand.
3. The `LeapTrigger_XXXX` has a collider that should detect object in question

Do you have any idea what I'm doing wrong?

**Comment by Martichoras** [comment]
Btw, I realized `HoldButtonPressed` wasn't changing with my implementation, so I changed it with `HoldButtonPressed = IsPinching;` from within a different script. now the two bools are changing together. I even added a collider to the`LeapTrigger_XXXX`, but I still don't get any reaction.

**Comment by grobm** [comment]
Do you need some help with this? I am in the process of implementing a STEM VR Lab and have Pinch and a wrist menu working.

**Comment by Martichoras** [comment]
Yes, that would be great. Right not we have implemented our own solution, but would like to use some of the functionalities of NewtonVR. Especially a solution to rigidbody collision with rigid-hand, and transfering of velocity to object i.e to enable tossing.

Do you have an idea about what might be wrong?

**Comment by naabel** [comment]
Great enthusiasm, while I'm closing this because we're not planning on Leap support at the moment, that for your support of NVR :+1:
