### ISSUE TITLE
Compiler errors in version 1.18

### ISSUE THREAD

**Issue by joostbos** [TomorrowTodayLabs/NewtonVR#116]
I just upgraded my project to the latest version (1.18) of NewtonVR in the asset store (including an update to Unity 5.4.3f1) and got two compiler errors:

Assets/NewtonVR/NVRDrawer.cs(19,30): error CS0115: `NewtonVR.NVRDrawer.OnNewPosesApplied()' is marked as an override but no suitable method found to override

Assets/NewtonVR/NVRDrawer.cs(55,33): error CS0115: `NewtonVR.NVRDrawer.DropIfTooFar()' is marked as an override but no suitable method found to override

Please advice how to solve this.

Thank you.

**Comment by keithbradner** [comment]
Make sure to delete your newton directory when upgrading. This shouldn't be an issue in 1.91

**Comment by keithbradner** [comment]
To further specify - I don't believe NVRDrawer exists anymore. It wasn't used for a while, I just got around to deleting it recently.
