### ISSUE TITLE
compiler errors using Newton VR 1.18 since upgrading SteamVR to 1.2

### ISSUE THREAD

**Issue by CasitaCreativa** [TomorrowTodayLabs/NewtonVR#118]
I am getting error  CS0117: `SteamVR_Utils' does not contain a definition for `Event' since upgrading to Steam VR 1.2. Any ideas anyone?

**Comment by ezonecom** [comment]
This pull request should fix your issues: https://github.com/TomorrowTodayLabs/NewtonVR/pull/117

**Comment by keithbradner** [comment]
Thanks, this should be fixed

**Comment by CasitaCreativa** [comment]
Thanks I appreciate your help!
