### ISSUE TITLE
SteamVR laser pointer

### ISSUE THREAD

**Issue by wadams201** [TomorrowTodayLabs/NewtonVR#12]
I'm experiencing an issue when I put a SteamVR_tracked controller and steamVR_laser pointer on an NVR controller, the laser pointer has two lasers which point in apparently random directions. I'm wondering if you have any idea what might be causing that behavior?

Thanks!

![laser pointer](https://cloud.githubusercontent.com/assets/17970035/14939521/81b1be68-0eff-11e6-8164-6f0324c3035d.PNG)

**Comment by keithbradner** [comment]
I'm not sure why the original line isn't pointing the correct direction, but the black one I think is the version on the physical controller. If you wanted to fix it for that implementation you'd need to add it to the destroy calls on the physical controller initialization. I'll come up with a longer term solution eventually but for now I've created NVRExampleLaserPointer and NVRExampleTeleporter to (somewhat) mirror the steamvr components. Just drop them on the controller gameobject to get them to work.

**Comment by wadams201** [comment]
Thanks a lot! I like your implementation better than theirs anyway. I can't get your teleporter to return a true on line 55, I'm trying to figure it out but you may have an idea of what's going on?

**Comment by keithbradner** [comment]
Glad that helped :) Not sure why you wouldn't get a true there. It should only be true for a single frame though when the state changes from "not pressed" to "pressed". If you want to have something that is true for every frame the button is pressed, use IsPressed. 
Alternatively, you may not be pressing the trigger down enough. I think it only registers PressDown when the trigger is past 50% pressed.
