### ISSUE TITLE
NVRSteamInputDevice Unable to Compile

### ISSUE THREAD

**Issue by GuessworkVRAndrew** [TomorrowTodayLabs/NewtonVR#121]
Hello, Steam VR recently updated their package to Version 1.2.0 which has removed SteamVR_Utils.Event.Listen and replaced it with a script called SteamVR_Events.**.Listen. I tried and was unable to fix the issue myself, but here is a link to the unity forum post describing the issue. Fairly urgent issue since it can no longer compile with the most recent version of unity and steam VR

**Comment by GuessworkVRAndrew** [comment]
https://forum.unity3d.com/threads/solved-steamvr-update-1-2-0-has-2-compiler-error.450834/
here is the link to the unity issue. Steam seems to have fixed this issue now but it looks like Newton hasn't been updated since the 1st of December. Thanks for the help!

**Comment by keithbradner** [comment]
Just submitted a fix for this a couple days ago. Are you on the latest github release on the main branch?

**Comment by GuessworkVRAndrew** [comment]
Just did, that fixed that issue. Interestingly enough, now, in my unity game, I can't grab things and in your example scene, the following error pops up for the Left and Right hand

ArgumentException: The Object you want to instantiate is null.
UnityEngine.Object.CheckNullArgument (System.Object arg, System.String message)

at line 243 in the code for NVRSteamInputDevice

dk2TrackhatColliders = GameObject.Instantiate(Resources.Load<GameObject>("ViveControllers/ViveColliders")).transform;

**Comment by GuessworkVRAndrew** [comment]
I deleted and re imported the package and that fixed it! No issues then I guess? Thanks anyways!
