### ISSUE TITLE
CalculateImpactVolume, in NVRCollisionSoundObject, can produce values greater than 1

### ISSUE THREAD

**Issue by massycat** [TomorrowTodayLabs/NewtonVR#125]
The CubicEaseOut method in NVRCollisionSoundObject does not do a maximum value check for the velocity so it can therefore cause the CalculateImpactVolume to return values greater than 1.
A fix is to add the maximum value check:
>         public static float CubicEaseOut(float velocity, float startingValue = 0, float changeInValue = 1)
>        {
>            if (velocity > NVRCollisionSoundController.Instance.MaxCollisionVelocity)
>            {
>                velocity = NVRCollisionSoundController.Instance.MaxCollisionVelocity;
>            }
>            return changeInValue * ((velocity = velocity / >NVRCollisionSoundController.Instance.MaxCollisionVelocity - 1) * velocity * velocity + 1) + startingValue;
>        }

**Comment by keithbradner** [comment]
Thanks for reporting. We need to take a better look at calculating the impact volume I think. For now, I don't think values greater than one are causing a bug so I'm going to leave as is. Added a card to trello to look at better calculation
