### ISSUE TITLE
D-pad input on SteamVR doesn't function as expected

### ISSUE THREAD

**Issue by justonia** [TomorrowTodayLabs/NewtonVR#127]
It is entirely the decision of the SteamVR library, but the EVRButtonId.k_EButton_DPad_* buttons do not map to the touchpad on the Vive controllers. Had you intended for them to? If not it might be nice to throw in the docs that this is the case and it's on the user to do the translation by analyzing the Axis0.

**Comment by justonia** [comment]
I have a heavily modified version of this library in my project and I adapted my previous workaround to this problem to the latest NewtonVR version. 

I first added a "None = 255" entry to the NVRButtons enum so there is a way to communicate a "null" button and thus also an axis that does not map to a dpad direction (imagine if you touch in center of the dpad). After adding this enum value I add a few sanity checks in the InputDevice subclasses to not call into their SDKs for that button enum.

I then added this to the NVRButtonInput class:

`public NVRButtons AsDPad
        {
            get
            {
                var axis = Axis;
                if (axis.sqrMagnitude < axisNoDpadThreshold) {
                    return NVRButtons.None;
                } 

                if (Vector2.Dot(Vector2.up, axis) > axisDPadDotThreshold) {
                    return NVRButtons.DPad_Up;
                }
                if (Vector2.Dot(Vector2.right, axis) > axisDPadDotThreshold) {
                    return NVRButtons.DPad_Right;
                }
                if (Vector2.Dot(Vector2.left, axis) > axisDPadDotThreshold) {
                    return NVRButtons.DPad_Left;
                }
                if (Vector2.Dot(Vector2.down, axis) > axisDPadDotThreshold) {
                    return NVRButtons.DPad_Down;
                }

                return NVRButtons.None;
            }
        }

        private const float axisNoDpadThreshold = 0.3f * 0.3f;
        private const float axisDPadDotThreshold = 0.5f;`

All those dot products might feel wasteful but it's easier to understand and obviously not an issue with only two hands active at once.

Edit: Can't seem to get the first half of the code to format correctly...

**Comment by keithbradner** [comment]
Thanks for reporting this but yeah I see this as a SteamVR issue. Kind of on them to document I think
