### ISSUE TITLE
New SteamVR Plugin update Breaks NewtonVR

### ISSUE THREAD

**Issue by Tanvarian** [TomorrowTodayLabs/NewtonVR#133]
New SteamVR Plugin update Breaks NewtonVR

You'll get an error message as such;
" NullReferenceException: Object reference not set to an instance of an object
NewtonVR.NVRButtonInputs.get_PressDown () (at Assets/NewtonVR/NVRButtonInput.cs:17) "

I haven't dug into it, though I can infer its likely due to SteamVR changing some of names of functions/variables that are no longer appropriate to call in NewtonVR's scripts.

Here's to hoping for a fix!

I'll dig around for a past version of steamVR and will post it here for a workaround if you've accidentally updated.

**Comment by keithbradner** [comment]
That's strange. I just updated and wasn't getting any errors. Be sure you delete the old version of steamvr before updating. They don't auto clean the folder like some plugins do. Can you try that and let me know if you're still seeing the same error?

**Comment by Tanvarian** [comment]
You're right. That did fix it. 

My apologies, and thank you for a quick reply.
Now back to work on the project.

Thank you so much for providing this tool for free to use.

**Comment by Tanvarian** [comment]
Ooop, thought I was getting a different bug related to my code, looks like I'm still getting the same error on that script, it's also listing the following if this helps.

//
NullReferenceException: Object reference not set to an instance of an object
NewtonVR.NVRButtonInputs.get_PressDown () (at Assets/NewtonVR/NVRButtonInput.cs:17)
NewtonVR.NVRCanvasInput.ButtonDown (Int32 index) (at Assets/NewtonVR/NVRCanvasInput.cs:339)
NewtonVR.NVRCanvasInput.Update () (at Assets/NewtonVR/NVRCanvasInput.cs:261)
//

(I need to try a clean unity project with nothing else quickly to make sure it's nothing on my end)

**Comment by Tanvarian** [comment]
Yes, new Unity project works fine.

So, I need to figure out what I've broken... Thanks!
