### ISSUE TITLE
NewtonVR crashes Unity 5.5.2f1 and 5.5.2p2

### ISSUE THREAD

**Issue by vitapoly** [TomorrowTodayLabs/NewtonVR#136]
Steps:
1. Create a new project
2. Add NewtonVR and SteamVR from AssetStore
3. Add NVRPlayer and enable Vive
4. Cause a runtime error in Start(), i.e., use this script:
     AssetBundle bundle = AssetBundle.LoadFromFile("non existing path");

Unity Crashes on any runtime error in the Start() function. I've attached a sample project.

Unity Version: 5.5.2f1
NewtonVR Version: 1.191 (Jan 18, 2017)
SteamVR: Version: 1.2.1 (Feb 25, 2017)

[Newton552Crash.zip](https://github.com/TomorrowTodayLabs/NewtonVR/files/835306/Newton552Crash.zip)

**Comment by SmartCarrion** [comment]
Thank you for reporting, i've been hitting all kinds of hard Unity crashes lately, and I can't seem to track them down!

back in 5.5.1p3 i updated Newton and was trying to enable oculus SDK alongside SteamVR and was getting crash on play.  So i pulled back on that work and just kept working on SteamVR.  Then lately i started getting crash on play even without Oculus SDK.  

My newest workaround I figured out was to have two versions of Unity installed, and alternate between them.  I can open the project once with each version, then if I close Unity and try again it is crash on play.    So then I open the other version of Unity and I can once again play the project.  CRAZY!

maybe i have a semi-silent Start error that is causing all of this...time to go hunting

**Comment by vitapoly** [comment]
I don't believe I had this issue in 5.5.1f2, but I need to confirm. But just FYI, I think it's really a Unity bug, so I submitted this same bug to Unity: https://fogbugz.unity3d.com/default.asp?889711_045e6ue6acbth0br

**Comment by SmartCarrion** [comment]
awesome, i reported it 10 days ago too and i bet it is related.

**Comment by vitapoly** [comment]
Unity says that they can't reproduce it. Can you download the project file and let me know if it crashes for you?

**Comment by SmartCarrion** [comment]
I finally tried running your project and it doesn't crash for me either.  I'm still getting crashes in my project though.  must be something more hidden, especially since my two version trick works.  What has been your solution?

**Comment by SmartCarrion** [comment]
I take it back, i closed unity, ran it again, closed unity, ran it again, now it is crashing

**Comment by SmartCarrion** [comment]
i'm using Oculus through SteamVR and 5.5.2p4.  Well it crashed once, now i'm struggling to repeat it

**Comment by SmartCarrion** [comment]
FYI, Unity 5.6.0f3 is working great, no more crashes for anything.

**Comment by keithbradner** [comment]
I'm going to close this since it seems like unity may have fixed it and it doesn't sound like a newton issue.
