### ISSUE TITLE
NullReferenceException from get_PressDown() in the first few frames after started

### ISSUE THREAD

**Issue by Time1ess** [TomorrowTodayLabs/NewtonVR#138]
Thanks for the efforts of the team to provide such a wonderful plugin. But I'm recently facing the problem that when I tried to test whether the `UseButtonDown` is true in `Update()`, it seems that in the first few frames it will raise `NullReferenceException`.

I checked the code and found that when it happens the `InputDevice` is `null` in `NVRButtonInput`. After a few frames, the `InputDevice` will be set up correctly, and  everything works fine, I believe the error occurs due to unfinished initialization process, but it bothers me when seeing these errors.

"NullReferenceException: Object reference not set to an instance of an object NewtonVR.NVRButtonInputs.get_PressDown () (at Assets/NewtonVR/NVRButtonInput.cs:17) "

Reproduce Steps:
1. Create a new project
2. Add NewtonVR and SteamVR from AssetStore
3. Add NVRPlayer and enable Vive
4. Add a script to test the `UseButtonDown` of an instance of the `NVRHand` class in `Update()`
5. Errors in console in the first few frames.

Relates:
#133 

The attached file is a modified version of `NVRButtonInput` and it works fine for me.

[NVRButtonInput.cs.zip](https://github.com/TomorrowTodayLabs/NewtonVR/files/888286/NVRButtonInput.cs.zip)

**Comment by keithbradner** [comment]
This should be fixed now. Let me know if you're still having issues
