### ISSUE TITLE
How to implement CollisionSoundController?

### ISSUE THREAD

**Issue by Oyshoboy** [TomorrowTodayLabs/NewtonVR#140]
Hi dear TomorrowTodayLabs, I want to implement CollisionSoundController, but it's not working.

What should I do, to make it working?

In my case I'm adding CollisionSoundController and NVR Collision Sound Object. But nothing happening.

Thank you!

**Comment by SmartCarrion** [comment]
Start by looking at the example scene, are the sounds working for you in there?  Then inspect how those items are constructed and copy them.

**Comment by Oyshoboy** [comment]
@SmartCarrion , sure, I'm already trying to to that, but I missing something, something not obvious
