### ISSUE TITLE
Controller UI Camera not assigned to Canvases

### ISSUE THREAD

**Issue by munkeyxis** [TomorrowTodayLabs/NewtonVR#143]
`DelayedCameraInit()` coroutine in NVRCanvasInput does not complete after creating the **Controller UI Camera**. Everything after the `yield return null;` never runs. When using the laser pointer feature, this causes the laser to be targeted to where ever the VR headset is pointing instead of acting as a straight line from the controller.

Steps to replicate:
Just open the NewtonVR's Example scene with a VR headset using motion controllers and **Laser Enabled** checked in **NVRCanvasInput**.
Turn to face the UI elements behind the door, a laser will be drawn from the motion controllers to where ever the headset is pointing.

**Comment by keithbradner** [comment]
Thanks for submitting, but I am not able to repro this with the steps you provided. Can you tell me what version of unity and newtonvr you are using? Also which headset and which sdk. Thanks!

**Comment by munkeyxis** [comment]
[NewtonVR] Version : 1.193. Found VRDevice: Oculus Rift CV1. Using Oculus SDK
Unity v5.6.0f3, Oculus Utilities v1.13.0, OVRPlugin v1.12.0, SDK v1.13.0.

**Comment by munkeyxis** [comment]
I'm noticing that any coroutine attached to the NVRPlayer gameObject is getting interrupted. Perhaps something is toggling the gameObject by disabling/enabling it, causing the coroutines to break?

**Comment by EUGD** [comment]
I just wanted to comment I was seeing the same thing. Lines from the wands to the same point, which is look-aimed.

**Comment by keithbradner** [comment]
Ah thanks, most of the time I test with Vive. I'll check this out

**Comment by felixosth** [comment]
I got this aswell. New pc install and new project. Very annoying bug.
[NewtonVR] Version : 1.193. Found VRDevice: Vive MV. Using SteamVR SDK

Any progress on when this is fixed?

**Comment by keithbradner** [comment]
Thanks for the reports everybody. Got the issue fixed. May be a bit before the asset store sees a fix though.
