### ISSUE TITLE
Main camera does not move with Player object.

### ISSUE THREAD

**Issue by EUGD** [TomorrowTodayLabs/NewtonVR#147]
Seems to be related to the script-created "Controller UI Camera", and thus possibly #143. Currently this camera is serving as the main camera, which I'm not sure is intended or not, and it fails to properly move with Player. The Head object, and its camera, does move as expected.

**Comment by SmartCarrion** [comment]
How can we replicate this? Does it happen in the example scene?  Sounds like it is in your scene and it isn't setup correctly...

**Comment by EUGD** [comment]
It is the example scene. Unchanged except for activating SteamVR in Player.

**Comment by EUGD** [comment]
resolved itself after reverting to a fresh install of 5.6.03f (from 2017 beta). pretty sure I had previously tried that already, but perhaps not with a total fresh install (uninstalling first)
