### ISSUE TITLE
Test Scene Interactions Not Working

### ISSUE THREAD

**Issue by stefang** [TomorrowTodayLabs/NewtonVR#148]
Hi, I can't seem to get the test scene working. The controller vibrates when there are collisions but nothing else happens. Did something break in 5.6.0?

SteamVR V1.2.1
Unity 5.6.0
NewtonVR 1.193

Running on up to date Windows 10

**Comment by keithbradner** [comment]
I'm sorry I'm not seeing this issue. You could try getting the latest from github (1.22). Seems unity hasn't accepted the recent version of the package into the asset store.

What hardware are you using? Vive Pre, Vive consumer, Oculus Touch?

**Comment by stefang** [comment]
Not sure why... Started working this AM.. Brilliant, and thanks :-)
