### ISSUE TITLE
Two Handed With Unique Interaction Points Per Hand

### ISSUE THREAD

**Issue by Kreyg** [TomorrowTodayLabs/NewtonVR#152]
Hi All!!

Firstly I love Newton VR! Its been a life saver. 

Sorry if this is the wrong place for this, but I was curious as to if Newton VR will ever support Two Handed Control with unique interaction points for each Hand (I know it supports two handed interactions, but as of now when I pick something up with two hands, it seems to just move weirdly and not control the way I thought it would). Ive been developing a weapon system, and I've hit a bit of a stumbling block with Two Handed Interactions. 

Not sure if this is something maybe planned (Checked Trello and didn't see anything .. unless I am blind as a bat!), and if not, if anyone reading this is able to implement something or give me a hand implementing I'd gladly talk about payment for the work. 

Thanks!!

**Comment by Kreyg** [comment]
Was able to get it working sort of. Still looking for any help on implementing unique interaction points per hand so that I can hold it with both hands at the same time, but have each hand be at different locations. As of now it lines them up so the controllers are like this 

p = controller 
/---- = gun
~ = bullets

/p-----p--- ~ ~ ~ 

I would love to be able to allow for unique points per controller and still maintain the two handed system. 

Thanks!

**Comment by Kreyg** [comment]
Well, I was able to get what I wanted, but I ditched NewtonVR altogether for something written from the ground up.

**Comment by keithbradner** [comment]
Glad you found a solution
