### ISSUE TITLE
NVR Interactable Item - OnUseButtonDown fires before 1f

### ISSUE THREAD

**Issue by Oyshoboy** [TomorrowTodayLabs/NewtonVR#172]
Hi, having a little issue, using OnUseButtonDown event inside Interactable Item, and it's used to fire earlier then controller trigger fully pressed.

It's fires on 0.5f state instead of 1.0f

Used to debug it with this:

`TrackedController.GetAxis(Valve.VR.EVRButtonId.k_EButton_SteamVR_Trigger).x;`

Where TrackedController is SteamVR_Controller with neccessary index.

**Comment by GierigBeefje** [comment]
Hi there,

I'm running into the same problem. Have you found a solution or answer yet for this?

Thanks in advance!

**Comment by Oyshoboy** [comment]
@GierigBeefje I'm assume it's not relevant anymore, so I'm closing this issue, there are bunch of new interaction framework.
