### ISSUE TITLE
NewtonVR compile error after SteamVR update.

### ISSUE THREAD

**Issue by JudgeGroovyman** [TomorrowTodayLabs/NewtonVR#190]
The new SteamVR update version 2.0 (came out just a few days ago) broke NewtwonVR for me.  I started a new project, imported NewtonVR, imported SteamVR and enabled it and there is a compile error in NVRSteamVRInputDevice which I'm not smart enough to solve.   I tried this on two different machines and it happened the same way on both.  In this new SteamVR 2.0 they have rewritten the input API so there are no longer any classes called SteamVR_Controller or anything like that.

Everything still works fine with the Oculus SDK.

**Comment by keithbradner** [comment]
Hi, yeah the new SteamVR plugin is not compatible with most existing frameworks. You can still use the SteamVR Unity Plugin v1.2.3 though, there is a download on the github here: https://github.com/ValveSoftware/steamvr_unity_plugin/releases/tag/1.2.3
