### ISSUE TITLE
Leap Motion Orion Support

### ISSUE THREAD

**Issue by robnewton** [TomorrowTodayLabs/NewtonVR#2]
I tried to use the physics interactions with DK2 and Leap Motion but got errors related to the Valve Hand references. Can you offer any advice on how I might be able to use this in conjunction with Leap Motion hands?

**Comment by Watchdodos** [comment]
We we're able to get NewtonVR working with Leap Orion, what were the errors you were running into?

**Comment by robnewton** [comment]
I was copying only the /NewtonVR folder from your Assets directory to mine and getting the following error:

> Assets/NewtonVR/NVRHand.cs(10,17): error CS0246: The type or namespace name `Valve' could not be found. Are you missing a using directive or an assembly reference?

Once I copied over the OpenVR plugin assets as well as the SteamVR assets, the compile errors went away.

Runtime is not working however. Started with the example scene. The NVR Camera was causing Unity to crash as soon as I hit play. (DK2 with OVR 8 installed in Windows 8.1 on Unity 5.3.2p3). So I disabled it and dropped in the Orion LHHeadMountedRig. Hitting play gives the following error many times then the scene pauses:

> NullReferenceException: Object reference not set to an instance of an object
>   at NewtonVR.NVRInteractables.Register (NewtonVR.NVRInteractable interactable, UnityEngine.Collider[] colliders) [0x00000] in Assets\NewtonVR\NVRInteractables.cs:25 
>   at NewtonVR.NVRInteractable.Start () [0x00000] in Assets\NewtonVR\NVRInteractable.cs:46 
> 
> (Filename: Assets/NewtonVR/NVRInteractables.cs Line: 25)

**Comment by robnewton** [comment]
Figured it out. NVRInteractables was not getting initialized. Added the following to the top of Register(), Deregister(), and GetInteractable() in NVRInteractables.cs.

`if (!Initialized)
                Initialize();`

**Comment by Watchdodos** [comment]
Ah, nice!
