### ISSUE TITLE
Loosing grabbed objects when shaking

### ISSUE THREAD

**Issue by spaggi** [TomorrowTodayLabs/NewtonVR#21]
First I'd like to say thanks a lot for releasing this excellent kit! This really makes developing for VR much easier!

That being said, I encountered the following issue:
When grabbing objects and shaking the Motion Controllers really quick the grabbed object drop out of the hand at some point. 

Do you have any idea how I can fix this in my project? Thanks!

**Comment by garytyler** [comment]
I had this issue with the Grab Snap Type set to Precision Snap and Rotation Snap but Simple Snap works as it should. Have you went back and tried Simple Snap?It looks like Precision and Rotation are new additions and I think it's a safe bet that this will get attention asap. This kit is so incredible. This is just what is needed to enable so many artists to apply their skills to VR hands on without taking a sabbatical. :)

**Comment by keithbradner** [comment]
You could increase the NVRInteractableItem.DropDistance. If you want to change that globally you can make it static too. I'd guess that's what your issue is.

**Comment by keithbradner** [comment]
Going to assume this was a satisfactory answer.
