### ISSUE TITLE
NVRInteractables.Deregister() implementation and/or usage example needed.

### ISSUE THREAD

**Issue by EUGD** [TomorrowTodayLabs/NewtonVR#22]
Destroying NVRInteractable-derived objects (or changing their colliders) can result in a bugged ghost entry in NVRHand.CurrentlyHoveringOver, which produces a number of buggy behaviors such as being able to grab the object from anywhere, or making the controllers vibrate perpetually (and probably more). It seems like NVRInteractables.Deregister (and the associated downstream functions in NVRPlayer & NVRHand) are made for this purpose, but it's unclear how they're intended to be used.

**Comment by keithbradner** [comment]
Whoop, will fix.
