### ISSUE TITLE
Should allow non-ghost renderers to be attached to NVRHand

### ISSUE THREAD

**Issue by dtsiknis** [TomorrowTodayLabs/NewtonVR#25]
NVRHand assumes any component of type Renderer attached to the hand gameobject is for use as a ghost renderer. It will then drive the enabling/disabling of those renderers which the ghost rendering logic which may not be desirable. 

I'm submitting a pull request that deals with this by introducing a GhostRenderer component for ghost renderers to inherit from, creating a clear distinction for these.

**Comment by taikuukaits** [comment]
I just wanted to add that a lot of this stuff could be delegated - it seems like the NVRHand is doing to much work. It could broadcast an event, then a listening HandRenderer could decide whether or not to enable/disable/ghost/not ghost.

Don't know how practical it would be but I too want to customize a lot of the hand render. I plan on animating and changing tips (similar to cosmic trip and budget cuts) so I have a lot to customize.

**Comment by dtsiknis** [comment]
Good point. Definitely a lot going on in NVRHand. I closed my PR as it isn't a practical solution once you factor in prefab components that come from SteamVR.

**Comment by keithbradner** [comment]
This is a good idea, not sure when we'll get to it though.

**Comment by naabel** [comment]
Planned feature, see Trello card (https://trello.com/c/PV9k81gj), closing.
