### ISSUE TITLE
Change controller to custom model

### ISSUE THREAD

**Issue by omerfaruk** [TomorrowTodayLabs/NewtonVR#3]
How can i change vive controller model with my custom hand models ?

**Comment by xanderhd** [comment]
I am curious of this as well. Both in Newton, and SteamVR. 

I thought there would be a controller component we would need to switch out or something

**Comment by keithbradner** [comment]
That sounds like a good idea. Thanks for the pull @omerfaruk, we'll check it out after gdc.

**Comment by keithbradner** [comment]
Implemented. Add a prefab to NVRHand's CustomModel and CustomCollider (for physical controller).

**Comment by dariomac22** [comment]
Hi team,
I'm having issues with collision detection with HTC Vive, Unity 3d and NewtonVR or Steam VR. I have made a tennis game (racquet as a custom controller and ball shooting towards me) but when I try hit the ball with a bit of speed, the ball passes through the racquet. If I slow down my hit speed the collision is detected and the ball bounces away like it should. My racquet has a simple box collider on it and the ball has a sphere collider. Is there a fix to this? (Seems to be an issue with VR, even when I try hit a sphere with a cube, simple shapes and colliders but when I increase my speed, they pass through each other). Any ideas how to fix this?

**Comment by keithbradner** [comment]
Hi, I'd recommend changing the ball and the racket's rigidbody to dynamic continuous physics and interpolation from none to interpolate. That should help significantly.

**Comment by dariomac22** [comment]
Cheers Zite, that got it working! 
Thanks again for the response.
