### ISSUE TITLE
Networked shared VR with NewtonVR

### ISSUE THREAD

**Issue by Vytek** [TomorrowTodayLabs/NewtonVR#30]
Is it possibile to use NewtonVR in networked shared VR, for example using DarkRift:

https://www.assetstore.unity3d.com/en/#!/content/16711
http://darkrift.ninjapokestudios.co.uk/

Is it complex? How to integrate this features?

**Comment by keithbradner** [comment]
Should be. Basically you just track the transforms like you would any other object. You'll have to do something tricky around multiple people trying to grab one object probably, but it should be okay.
