### ISSUE TITLE
Letter Spinner Momentum

### ISSUE THREAD

**Issue by ghost** [TomorrowTodayLabs/NewtonVR#31]
Hi, I was wondering if there is a way to prevent the letter spinner from doing it's little "wobble" from the momentum it has? So following the user's grab point and instantly stopping where they hold their hand.

Thanks

**Comment by MarkwarNickA** [comment]
The wobble was dampened by increasing the angular drag of the LetterSpinner Rigidbody to 5. The LetterSpinner is an implementation example, so we probably won't touch it anymore. Another way to remove the spin might be to kill the angular velocity when the InitialAttachPoint lies on a line drawn between the point of rotation and the transform of NVRHand.

**Comment by naabel** [comment]
Closing, the wobble was dampened by increasing the angular drag of the LetterSpinner Rigidbody to 5. The LetterSpinner is an implementation example, so we probably won't touch it anymore. Another way to remove the spin might be to kill the angular velocity when the InitialAttachPoint lies on a line drawn between the point of rotation and the transform of NVRHand.
