### ISSUE TITLE
NVRHand fails to initialize when unloading and reloading NVRHand component

### ISSUE THREAD

**Issue by dtsiknis** [TomorrowTodayLabs/NewtonVR#36]
When unloading one scene and loading a new scene each with their own player rigs, The NVRHand components being unloaded receive a render_model_loaded message after being destroyed. This seems to cause an exception that keeps the new NVRHand component from properly initializing.

Solution is to deregister from the event in the OnDestroy callback of NVRHand. See attached pull request for the fix.

**Comment by DevenSmith** [comment]
I fixed this by adding a OnDestroy to the NVRPlayer and setting the NVRInteractables.initialized bool to false again.

**Comment by DevenSmith** [comment]
So I had tried the recommended fix here before I did mine and left it in which I do not recommend it ended up causing an issue were when doing all the initial set up one hand would always set up wrong being stuck in a physical state.

**Comment by keithbradner** [comment]
Thanks for reporting. This should have been fixed in 0.9
