### ISSUE TITLE
NVRInteractable

### ISSUE THREAD

**Issue by smygarn** [TomorrowTodayLabs/NewtonVR#38]
I implemented a class that enabled/disabled all sub-rigidbodies on attach/detach. I think that function should be of better use in NVRInteractable baseclass. 

It's really easy and you will be able to move the control panel for example.

It will also solve the issue of the cube with the button. :)

My class:

```
   using System.Linq;
   using System.Collections.Generic;

public class NVRInteractableItemPanel : NVRInteractableItem
{
    private Rigidbody[] bodies;
    protected override void Awake()
    {
        base.Awake();

    }

    protected override void Start()
    {
        base.Start();
        bodies = GetComponentsInChildren<Rigidbody>().Where(x => !x.isKinematic).ToArray();
    }

    public override void BeginInteraction(NVRHand hand)
    {
        foreach (var item in bodies)
        {
            item.isKinematic = true;
        }

        base.BeginInteraction(hand);

    }

    public override void EndInteraction()
    {
        foreach (var item in bodies)
        {
            item.isKinematic = false;
        }
        base.EndInteraction();
    }
}
```

**Comment by keithbradner** [comment]
Thanks for the input. I'm don't think I really want to turn things kinematic while held though. I think some kind of additional velocity data to child rigidbodies is the solution. Not sure...
