### ISSUE TITLE
Steam VR v1.0.8 has model as child of controller.

### ISSUE THREAD

**Issue by johnshaughnessy** [TomorrowTodayLabs/NewtonVR#4]
When I upgraded to Steam VR v1.0.8 I had to change a line in NVRHand.cs:

return this.GetComponent<SteamVR_RenderModel>().renderModelName;

to

return this.GetComponentInChildren<SteamVR_RenderModel>().renderModelName;

because the model gameobject is a child of the controller gameobject in the [CameraRig] prefab that comes with Steam VR v1.0.8

**Comment by garytyler** [comment]
thanks :)

**Comment by xanderhd** [comment]
Hi, When i updated i had issues as well. I tried your method. Well, i had to do:
              return this.GetComponentInChildren<SteamVR_RenderModel>().renderModelName;
but am still facing an issue.
 When i test my game, the controllers start off black. I need to hit the steam button, and then hit it again to make them pop up white, and be able to grab stuff. 

Has anyone else encountered this issue?

**Comment by keithbradner** [comment]
Thanks for the heads up guys. The most recent update should fix most 1.0.8 issues. We'll do more thorough testing post gdc.
