### ISSUE TITLE
Link controller trigger to start animation

### ISSUE THREAD

**Issue by weemct** [TomorrowTodayLabs/NewtonVR#44]
Hi, I'm new to unity VR and am trying to have an animation start playing when I pick up an object. I'm using the HTC VIVE. So far, using your intractable item and attach point  scripts I can pick the object up but i cant figure out how to get the animation to play. Basically, its a greetings card that i want to open when its picked up. So far my script (that doesn't work) looks like this: 

using UnityEngine;
using System.Collections;

public class PlayAnimation : MonoBehaviour
{
    // Update is called once per frame
    void Update()
    {
        if (Controller_Hand.GetPress(triggerButton))
        {
            GetComponent<Animation>().Play("Take 001");
        }
    }
}

Can you please help me? I'm a bit over my head here. Thank you,

**Comment by toto5100** [comment]
You did not declared Controller_Hand. See if something like this works : 
using UnityEngine;
using System.Collections;

```
public class PlayAnimation : MonoBehaviour
{

public NVRHand controller;
// Update is called once per frame
void Update()
{
if (controller.UseButtonPressed == true)
{
GetComponent().Play("Take 001");
}
}
}
```

Dont forget to assign to `controller` the controller's gameobject.

**Comment by keithbradner** [comment]
This should also be easier now in 0.9!
