### ISSUE TITLE
How to change the grip functionality to trigger functionality?

### ISSUE THREAD

**Issue by dre4mer12345** [TomorrowTodayLabs/NewtonVR#48]
Hi there, I've been experimenting with newton VR for the last couple weeks it's pretty sweet thanks for your work on this!! 

I've been trying to figure out how to map the grip functions instead to the trigger though. It seems like it should be straight forward but so far I can't seem to figure it out.

Thanks for any assistance!

**Comment by hcorion** [comment]
You need to go into NVRHand.cs (in /Assets/NewtonVR/) and change this line (currently line 13): 
`private Valve.VR.EVRButtonId HoldButton = EVRButtonId.k_EButton_Grip;`
to
`private Valve.VR.EVRButtonId HoldButton = EVRButtonId.k_EButton_SteamVR_Trigger;`
And if you wanted to change the 'use button' go to (currently) line 19 and change:
`private Valve.VR.EVRButtonId HoldButton = EVRButtonId.k_EButton_SteamVR_Trigger;`
to whatever you want, for example, to use the touchpad button:
`private Valve.VR.EVRButtonId UseButton = EVRButtonId.k_EButton_SteamVR_Touchpad;`
which is slightly awkward for the user, but easier for them to understand IMO.

**Comment by naabel** [comment]
As per comment above, this can be set by the EVRButtonId fields in NVRHand to the respective EVRButtonId enum. Closing

**Comment by spee** [comment]
changing the code in NVRHand — private fields even — feels like a hack that you could lose when you want to update Newton in your project. shouldn't it be done by overriding in a subclass?

edit: sorry, this seems to not apply anymore, as the current version uses public properties.
