### ISSUE TITLE
NVRInteractables sometimes lose all momentum when thrown

### ISSUE THREAD

**Issue by SmartCarrion** [TomorrowTodayLabs/NewtonVR#50]
About 50% of the time my interactables don't throw correctly.  They either stop forward progress and drop by gravity, or they sometimes wildly bounce backwards.  They may even get a momentum boost forwards sometimes, but i can't tell if that is just my throw.

It seems to be enhanced by swinging my arm fast, sometimes... but it happens at slow and fast speeds.  I can't reliably reproduce it and it has been very hard to track down. It can happen when i 'let go' in the middle of an arm swing or at the end.  When i flick my wrist, or keep it locked. Has anyone else seen this issue?

Troubleshooting: 
I tried (briefly) changing the layer of the thrown item to something that doesn't interact with the layer the controller is on.

I can't figure out the root cause of this one, please post if you have an idea!  I can post a video if that helps.

**Comment by SmartCarrion** [comment]
This is definitely performance based.  It is very much less a problem when i build the game, i see in consistently in the editor, but it is better when playing at 90 fps.

Maybe something with missing physics frames?

**Comment by keithbradner** [comment]
This should have been fixed when we switched to using OnNewPoses instead of fixedupdate. Are you seeing this in the most recent version of NewtonVR?

**Comment by SmartCarrion** [comment]
Joyous celebration that worked!  I thought i was tracking it well but i must have missed a version.  Thanks for your help.
