### ISSUE TITLE
Tracking becomes laggy when NVRInteractableItem when gameObject.activeSelf is toggled.

### ISSUE THREAD

**Issue by treefortress** [TomorrowTodayLabs/NewtonVR#53]
We have a paddle object(NVRInteractableItem) that is always attached to your hand (NVRHand). Depending on the state of the hand, we want to show/hide the attached paddle.

The issue is, if we set paddle.IsActive = false in one frame, and then paddle.IsActive=true in a subsequent frame, tracking becomes very slow, lagging far behind the real world position. Primarily on rotation it seems. 

Something like this should replicate the issue: 

void Start(){
paddle,transform.position = transform.position;
paddle.transform.rotation = transform.rotation;
nvrHand.BeginInteraction(paddle);
paddle.gameObject.SetActive(false);//Omit this line, and tracking is great. 
}

void Update(){
paddle.gameObject.SetActive(true);
}

**Comment by keithbradner** [comment]
I believe this was fixed some tiem ago. At least as of 0.9.
