### ISSUE TITLE
Adding custom hand models does not stop controllers from showing up

### ISSUE THREAD

**Issue by SmartCarrion** [TomorrowTodayLabs/NewtonVR#54]
Seems like when you add hands, it should be easy to choose whether to show the controllers or replace that model entirely.  Or automatically replace the old controller visual, although that is nice to use when 
lining up the new model

When my new hands spawn, they are calling "SteamVR_Utils.Event.Send("hide_render_models", true);" after a couple frames, but it doesn't consistently turn them off.  it mostly turns them off, but if you hit a button sometimes one of the physical controller models will still be there, or will pop back into existence.

**Comment by SmartCarrion** [comment]
The only thing i've found to work is running the code below from a high level script. It runs anytime a controller is enabled (so anytime grip is pressed without grabbing something, and at start).  If anybody has a better solution let me know!  This is definitely overkill.

`public void HideControllerModels()
    {
        foreach (Transform t in GetComponentsInChildren<Transform>())
        {
            if(t.name == "Model" && t.GetComponentInChildren<MeshRenderer>(true)!= null)
            {
                t.GetComponentInChildren<MeshRenderer>(true).enabled = false;
            }
        } 
    }`

**Comment by flarb** [comment]
This is the one feature from my own controller code that I think NewtonVR lacks. For my own stuff, I have custom hand models which react to input.

If you click the grip button and you're not colliding with a grabbable object, it triggers a quick grip/release animation.

If you pick something up, it hides the hand so you just see what you are grabbing.

When you drop the object, it shows the hand again, and triggers a release animation to show that you dropped it.

Is there anyway to do this with Netwon? I'm not quite sure.

**Comment by SmartCarrion** [comment]
Newton does have the ability to hide all controller models when you grab something, that is a nice and simple checkbox on NVRPlayer.  As for making your models animate with button presses, i have implemented that too, but that is very custom and doesn't seem necessary for this plugin.

**Comment by flarb** [comment]
Ah very cool, I'll dig into it (didn't see any documentation about it).

**Comment by flarb** [comment]
BTW as for animation stuff--I was thinking of a more generalized event system where you could wire up methods/delegates to each hand controller that fire off on input (button presses, touch pad, etc.) So you could use it for anything, not just animation.

**Comment by flarb** [comment]
Oh and yes, I have this same bug too.

**Comment by naabel** [comment]
Should be fixed in (https://github.com/TomorrowTodayLabs/NewtonVR/commit/98858b22c395f5f527233808b99686a2cbf66bdd)
, did that squash the problem?

**Comment by naabel** [comment]
Looks like it's fixed, closing
