### ISSUE TITLE
Adding custom models removes albedo texture and changes color to white

### ISSUE THREAD

**Issue by flarb** [TomorrowTodayLabs/NewtonVR#55]
I've added some custom hand models to my controllers--in addition to the default vive controllers not disappearing, it also changes the albedo textures to white on the hands. Clicking the grip buttons alters their translucency, but they stay white.

**Comment by TrebuhD** [comment]
I've worked around this by changing line 698 in NVRHand.cs from:

`Color transparentcolor = Color.white;`

to:

`Color transparentcolor = CustomModel.GetComponent<Renderer>().sharedMaterial.color;`

and commenting some lines in NVRHelpers.cs. [Here's](https://github.com/TrebuhD/NewtonVR/commit/f69fb4815d5e07227080ca68f7cd96198dab307f) the relevant commit from my fork.

**Comment by naabel** [comment]
Closing, as this will be corrected and expanded as an added feature in NewtonVR, see Trello card (https://trello.com/c/lHaOStSX)
