### ISSUE TITLE
Ghost Controllers seem to cause flickering of "held" objects.

### ISSUE THREAD

**Issue by SpoofMutt** [TomorrowTodayLabs/NewtonVR#57]
FYI, I disabled all the ghost controller code and just went with the standard models. After doing so, the held objects quit their flickering effect.

**Comment by keithbradner** [comment]
This seems to be fixed as of 0.9

**Comment by spee** [comment]
I still have flickering held objects (using 0.9+, downloaded from Github today). What should be disabled to fix it?

**Comment by U5man** [comment]
Just updated to version 1.0 and I am also having the flickering issue when a interactable item is picked up. Even in the demo scene.
