### ISSUE TITLE
Grabbing the same object with both hands causes NaN velocity and angular velocity

### ISSUE THREAD

**Issue by cdbarron** [TomorrowTodayLabs/NewtonVR#59]
Hey guys, first of all, thank you for making this! The interaction system is so kickass

I ran into an issue when attempting to grab an object with both hands at the same time. Unity gives this error:

rigidbody.velocity assign attempt for 'NVRExampleDrawer' is not valid. Input velocity is { NaN, NaN, NaN }.
UnityEngine.Rigidbody:set_velocity(Vector3)

rigidbody.angularVelocity assign attempt for 'NVRExampleDrawer' is not valid. Input angularVelocity is { NaN, NaN, NaN }.

**Comment by naabel** [comment]
Closing, this will be fixed when we implement multi-handed item interaction, see Trello card (https://trello.com/c/B0axSuZ6)

Linked to https://github.com/TomorrowTodayLabs/NewtonVR/issues/47

**Comment by cdbarron** [comment]
Thanks! Is there anything I can do to prevent the game from crashing in the meantime?

**Comment by provencher** [comment]
Has there been any progress on this? ->  multi-handed item interaction

**Comment by keithbradner** [comment]
pretty sure we implemented two handed interaction a couple versions ago

**Comment by provencher** [comment]
Ah okay. Might want to update the Trello then

**Comment by keithbradner** [comment]
Good point, thanks
