### ISSUE TITLE
Doesn't compile: NVRCollisionSoundProvider not defined

### ISSUE THREAD

**Issue by forrestthewoods** [TomorrowTodayLabs/NewtonVR#60]
`public class NVRCollisionSoundProviderUnity : NVRCollisionSoundProvider`

No where in the project is `NVRCollisionSoundProvider` defined. You can do a search on GitHub repository and it won't be found. Someone probably forgot to commit some files...

**Comment by naabel** [comment]
A wetware error on my part (never commit at 2 am before a early morning flight. I've submitted a dummy file so it will compile, and am having someone get the correct submitted today/tomorrow.

[https://github.com/TomorrowTodayLabs/NewtonVR/commit/9a4698774b70b0fa592c5aba0210cd9687236947]

**Comment by naabel** [comment]
Correct file committed.
