### ISSUE TITLE
SteamVR plugin versioning

### ISSUE THREAD

**Issue by IntegersOfK** [TomorrowTodayLabs/NewtonVR#61]
Thank you for this repository; I don't know how far along I'd be in my project without your help.

I had already added the [SteamVR Plugin](https://www.assetstore.unity3d.com/en/#!/content/32647) to my project before I imported the NewtonVR assets and it threw an error with functions relating to the SteamVR Plugin. Making a new project and importing all the assets including the NewtonVR version of SteamVR Plugin works as expected.

It seems the SteamVR plugin has updated since the latest NewtonVR release and now Newton VR's version of the SteamVR plugin keeps popping up asking me to download the latest version of SteamVR. I know from before that the latest version of SteamVR throws an error with NewtonVR, so should I hide that window forever?

I would recommend adding a section to the readme which explains this nuance; that a) you must not have added SteamVR Plugin to your project before importing NewtonVR and b) you must not update the SteamVR plugin that comes with NewtonVR.

So I don't really have an issue I'm just trying to get a sense of what the procedure is for using the library as it relates to the SteamVR plugin. Moving forward, how and what should we (users of NewtonVR) update? I'll just keep pulling the latest repo changes from here and that'll take care of the SteamVR stuff entirely so I can hide the window and forget about it?

Thanks for any insights, and thanks again for such a useful toolset!

**Comment by naabel** [comment]
Hey Integers,

I updated the UnityPackage to include the latest SteamVR plugin and NewtonVR. I took your advice and updated the notes to specifically tell people they don't need to overwrite their current version of SteamVR. A good way to keep NewtonVR updated is to clone the repository in a separate location, and make a symbolic link between Assets/NewtonVR in the repository and NewtonVR in your Unity project.

https://github.com/TomorrowTodayLabs/NewtonVR/commit/4e6fad23a107bf40c8f28721cdccc8580122c39f
