### ISSUE TITLE
Laser of ghost controller does not match laser of visible controller.

### ISSUE THREAD

**Issue by SpoofMutt** [TomorrowTodayLabs/NewtonVR#64]
Indication of misalignment of translation/rotation of laser end points.

**Comment by SpoofMutt** [comment]
May be indication of why ghost controllers flicker held objects. See issue #57.

**Comment by keithbradner** [comment]
Thanks for reporting. This probably needs to get fixed.

**Comment by keithbradner** [comment]
Took quite a while to get this fixed, but it has been fixed in 1.16. Thanks again.
