### ISSUE TITLE
Hand doesn't reappear if holding something that is force detached

### ISSUE THREAD

**Issue by SmartCarrion** [TomorrowTodayLabs/NewtonVR#66]
When a held object is disabled and force detached, the hand stays inactive if Make Controller Invisible on Interaction is set. It should instantly reappear I think.

it reappears if you let go of the grip buttons and then functions normally.

**Comment by keithbradner** [comment]
Thanks again @SmartCarrion. I believe this was fixed in 0.9. Let me know if you're still seeing the issue.
