### ISSUE TITLE
Interaction does not work on Unity 5.4.1f1

### ISSUE THREAD

**Issue by designnomad** [TomorrowTodayLabs/NewtonVR#68]
Hello, 

I am so excited to start using NewtonVR toolkit, yet 
it seems like trigger based interaction does not work on
my Unity 5.4.1f1. 

Thanks,
Haejin

**Comment by SmartCarrion** [comment]
It is working fine for me.  Check which button you are pushing.  The interaction is using the grip buttons, not the trigger button.

**Comment by SmartCarrion** [comment]
It can be altered by altering a little bit of code in NVRHand.

**Comment by designnomad** [comment]
Thanks for quick response SmartCarrion! I had no doubt using trigger as an input - my bad. 
Thanks for correction and it feels super great to finally interact with elements.
