### ISSUE TITLE
UI Indicator is Game Screen Size Dependant

### ISSUE THREAD

**Issue by TheCarow** [TomorrowTodayLabs/NewtonVR#69]
When I resize the game window (editor or as an executable), the UI indicator offsets.

Solve:

In NVRCanvasInput.cs, replace

`PointEvents[index].position = new Vector2(Screen.width, Screen.height);`

with

`PointEvents[index].position = new Vector2(ControllerCamera.pixelWidth * 0.5f, ControllerCamera.pixelHeight * 0.5f);`

**Comment by keithbradner** [comment]
Pretty sure I fixed this in ver 0.9
