### ISSUE TITLE
Latest commit for checking held distance is incorrect

### ISSUE THREAD

**Issue by justonia** [TomorrowTodayLabs/NewtonVR#70]
The math on the latest commit is incorrect when calculating ClosestHeldPoint and determining distance. 

It should be:
 `ClosestHeldPoint = this.transform.InverseTransformPoint(hand.transform.position;`.

As you have implemented, ClosestHeldPoint will always be Vector3.zero since you subtract the same transform from itself. While this may seem to work correctly in your test scene, it is only by coincidence. If you create a non-uniform sized object like a plank with its origin its center of mass, when you grab it on an end and move it around you will very easily drop it despite having a very large drop distance (>=.5). 

By using my math you get the exact point in local space of the object where the hand grabbed it. This means you must also change `DropIfTooFar` to calculate distance like this:

`float distance = Vector3.Distance(AttachedHand.transform.position, this.transform.TransformPoint(ClosestHeldPoint));`

**Comment by keithbradner** [comment]
Thanks for reporting! Think this was fixed in 0.9. Let me know if it's still an issue.
