### ISSUE TITLE
Rigidbody.angularVelocity assign attempt is not valid. Input angularVelocity is {NaN, NaN, NaN}

### ISSUE THREAD

**Issue by nandersonD5T** [TomorrowTodayLabs/NewtonVR#72]
I'm running into a problem. I have a longer string of objects that are jointed together to create a rope/cable. In the scene I'm working on the player has to pull that cable through a room. I have each segment of the cable attached together with configurable joints and they have an NVR Intractable Item script and collider. 

Currently if you pull the cable slowly it's fine. The problem is if you pull to fast or to hard I suddenly get a spam of error messages and the game screeches to a halt. It doesn't crash but it becomes so slow that the scene disappears and Steam VR shows up.

The errors include: 
Invalid AABB aabb
Invalid AABB result
Invalid AABB rkBox
IsFinite(d)
IsFinite(outDistanceForSort)
Converting invalid MinMaxAABB

All of these error are thrown anywhere from 100 to almost 1000 times before I get the scene to stop playing, they dont have any other description, and double clicking them doesn't bring you to any code. Then I get 4 errors that says

rigidbody.angularVelocity assign attempt for 'whatever object' is not valid. Input angularVelocity is {NaN, NaN, NaN}

and double clicking on those 4 brings up the NVR Intractable Item Script. Has anyone else had this occur or might know what is causing it? I've been looking around for answers about the errors and one thing mentions dividing by zero someplace but I wasn't sure where that would occur or if that's even the problem.

Also I am running Unity 5.4.1f1

**Comment by SmartCarrion** [comment]
I don't know what is causing your joint problem, but I get those newton
errors too. I haven't fully tracked it down because it doesn't seem to
cause any real problems for me. Something with computing the average
velocity I think. If it doesn't have enough frames of existence, it is
trying to average a null value with the actual positions/velocity.

Are you instantiating or pooling those segments? So after you pull some it
is spawning fresh ones with no history?

**Comment by nandersonD5T** [comment]
No, all segments are already in the scene at start time. If I pull slowly it works fine, usually. Only when I pull to fast  at any point does it explode. And the errors that do link to the NVR Intractable script, the 4 that say something about angularVelocity, only show for one segment. So that makes me think that it's just happening on a single object and not necessarily the joints. Usually joint problems just appear as the rope scattering in all directions but doesn't slow the scene to a crawl. 

I saw the line of code where it calculates average velocity so I'll look at that so see if there's something I can tweak or figure out. I have some other ideas to try as well. 

It just aggravates me getting errors with no description or link to code like those Invalid AABB errors. Makes it incredibly tedious to debug when you don't know where to start.

**Comment by nandersonD5T** [comment]
So narrowed it down a bit. I've figured out that the errors are happening between the controller and whatever segment it is grabbing currently. First thing I looked at was I did have another custom script that I had forgot about. 

Because of how many links are in the rope and the limits I've had to put on the angular movement to make it more rigid the default grab interaction from NVR Intractable Item wasn't strong enough to pull the rope. The connection just breaks the moment you try to pull. I didn't see where in the NVR the connection was made so I wasn't sure how to increase the strength of it. So I made a custom script that  would create a very strong spring joint between the currently grabbed item and the controller, and the joint is destroyed when you let go. 

Initially I tried taking this script off thinking it was causing the problem. Im sure it was part of it however I still got the errors to appear if I bent the rope at a bad angle even without the custom script on. The other problem this rises is without that custom script to increase the strength of the interaction I cant pull the cable. 

So this doesn't really help to solve anything. The problem is still in NVR Intractable Item somewhere from what I can tell. probably with the calculations at some point between the controller and object. but I wanted to at least add the info.

**Comment by SmartCarrion** [comment]
Try increasing the mass of the one you grab when you grab it. Like by 100x.
maybe it doesn't have enough force to move the big string behind it. That's
really supposed to be the whole point of newton, little things don't push
big things.

**Comment by keithbradner** [comment]
This should have been fixed in 0.9
