### ISSUE TITLE
[feature request] Input Injection

### ISSUE THREAD

**Issue by noirb** [TomorrowTodayLabs/NewtonVR#74]
It would be incredibly useful for my application to be able to control NewtonVR objects without necessarily needing a Vive connected. Scenarios I'm working on include allowing AI agents to use NewtonVR for their interaction with the world and playback of a recorded play session (in which the recording may take snapshots of the world at regular intervals around 0.1s rather than recording every frame).

Setting the public properties on NVRHand goes pretty far and I've got grasping & manipulation working fairly well (though it feels a bit hacky and goes crazy if the Vive is connected), even with a recorded session with a fairly coarse snapshot interval, but where it begins to really fall apart is in NVRInteractableItem. Since the recordings set new positions at intervals with several frames between them, the velocity history stored by NVRInteractableItem is mostly filled with zeroes (since there's no motion between timesteps in the recording), and an action like throwing cannot be reproduced.

So, my suggestion is: provide virtual abstract interfaces for NVRHand and NVRInteractableItem to pull their input data from. Default implementations would just take data directly from SteamVR and the object's transform, respectively, (as is done, now) but developers would be able to easily replace these implementations with their own class providing pose & button state information to the hands and velocity information to the InteractableItems from other sources as needed.

Perhaps NVRHand would look something like:

``` c#
    public class NVRHand : MonoBehaviour
    {
        protected NVRHandInputSource inputSource;
        ....

        public NVRHand()
        {
             inputSource = new SteamVRInputSource(controllerIndex);
        }

        ...

        protected virtual void Update()
        {
            if (intputSource == null)
                return;

            Inputs = inputSource.GetInputState();

            HoldButtonPressed = Inputs[HoldButton].IsPressed;
            HoldButtonDown = Inputs[HoldButton].PressDown;
            HoldButtonUp = Inputs[HoldButton].PressUp;
            HoldButtonAxis = Inputs[HoldButton].SingleAxis;

            UseButtonPressed = Inputs[UseButton].IsPressed;
            UseButtonDown = Inputs[UseButton].PressDown;
            UseButtonUp = Inputs[UseButton].PressUp;
            UseButtonAxis = Inputs[UseButton].SingleAxis;

            ...
        }

        ...
    }
```

SteamVRInputSource would then perform the same GetPressDown/GetPressUp/etc calls currently being done in NVRHand.Update, but I could also provide an alternate InputSource implementation which provided values from somewhere else.

Does this sound reasonable? :)

**Comment by noirb** [comment]
I've started on this in my fork. [See comparison against TomorrowTodayLabs master here](https://github.com/TomorrowTodayLabs/NewtonVR/compare/master...noirb:input-injection). Should be ready to make a PR soon, but thought I'd mention earlier in case anyone had some criticisms or other feedback on my approach so far. 

My overall goal was to add an abstraction layer between NVRHand (and related components) and the input source for controlling it, and I have tried to avoid changing the pre-existing behavior as much as possible.

The solution I'm working on is to provide a [NVRDriver](https://github.com/noirb/NewtonVR/blob/input-injection/Assets/NewtonVR/NVRDriver.cs) class which is responsible for updating the other NVR components on a character. So the NVRHands no longer update their own button states, they rely on an NVRDriver to set them each frame and the hands just read whatever the current state is. Similarly they don't set their own positions, the NVRDriver is responsible for updating them.

At the moment I just one have one driver implemented, [NVRViveDriver](https://github.com/noirb/NewtonVR/blob/input-injection/Assets/NewtonVR/NVRViveDriver.cs), which handles pretty much all of the SteamVR-specific details that were previously present in NVRHand and NVRPhysicalController. It also adds any necessary SteamVR components to the GameObjects the NVRHands and NVRHead are attached to, so apart from setting up a rig with NVR components and a camera, the user doesn't need to do anything except attach the NVRViveDriver to use a Vive on their character (and, hopefully, using some other hardware or no hardware at all should just require swapping the NVRViveDriver for a different driver script rather than building different Prefabs for every scenario).

I plan on also adding a sample driver showing that NVRHands can be used for interaction with AI characters without any hardware attached, which should hopefully help nail down the API needed in NVRDriver and demonstrate its value ;)

**Comment by keithbradner** [comment]
Ah, sorry I haven't been keeping up with issues, but there's a big abstraction update coming soon that does just this. There isn't a "driver" for non tracked controllers, but making one should be easy enough (ish?)

**Comment by noirb** [comment]
Ah, cool. Looking forward to it!

**Comment by keithbradner** [comment]
I think this abstraction is the closest we're going to get to this request. Glad you've got a fork up though :)
