### ISSUE TITLE
Implemented two handed interactions. 

### ISSUE THREAD

**Issue by SmartCarrion** [TomorrowTodayLabs/NewtonVR#75]
Hi all, I made a nice simple implementation of two handed interactions for NVRInteractableItem while on a road trip today. I will test it out when I'm back in VR in a few days.  Send me a note if you want the code, or give me pull request permissions and I'll spend some time to cleanly integrate it.

**Comment by SmartCarrion** [comment]
My two handed interactions are working really well.  I made a check box for toggling it to be on only certain items.  It is a simple implementation, just using the average point between the two hands as the pickup transform, but it is very intuitive for my game.  Might not be perfect for holding a gun, but who knows.  

Let me know if you need it!

**Comment by smygarn** [comment]
I'd like a copy of your implementation!

**Comment by SmartCarrion** [comment]
Hey, I've been anticipating the big reworking of the code base they are working on, so I haven't spent the time porting this back to work on the current version.  Here are the basics that can help get you started if you need it.

The overall idea I found most appropriate was to create a new transform when the object is grabbed by a second hand.  The new transform tracks the position halfway between the hands, and rotates to point from one hand to the other.  This effectively smooths the input between the hands, and the only thing about the InteractableItem that needs to change is the parent of the 'InteractionPoint'.  The interaction point starts tracking the new two-handed transform instead of tracking the controller.  Nice and neat, all the old velocity history works, and it can cleanly go back to single-handed mode when one hand drops.

If I remember all the changes correctly, I had some basic variables added to all Interactables, some specific code to InteractableItems, then I had to modify the start and end interactions on NVRhand.  Here are those files, although they have a few other changes in them too that are important to my particular game.  (unity events, a 'hover closest' function for applying highlighting to objects that are currently grabbable...probably some other stuff.  i.e. i'm not saying this is cleanly installable, but I wanted to get the idea out there)

[HERE IS THE FILE: two handed interaction.zip](https://github.com/TomorrowTodayLabs/NewtonVR/files/574572/two.handed.interaction.zip)

let me know if i can help

**Comment by SmartCarrion** [comment]
i ported all my code over to the new version and it made me realize how many little functions I'd added over time.  feels like we need a better system for submitting improvements...

**Comment by pkarjala** [comment]
@SmartCarrion If you have forked the NewtonVR project, look into [Pull Requests](https://help.github.com/articles/about-pull-requests/), which is the way that proposed changes should be made to an existing project!

**Comment by keithbradner** [comment]
I'm going to try and look more seriously at pull requests in the future. Closing this issue for now. If you feel like it, feel free to fork the repo and submit a pull request. I may or may not take your pull but you can always point people at your fork!
