### ISSUE TITLE
NVR Canvas Input Cursor is no longer aligned with controller point direction

### ISSUE THREAD

**Issue by Rawrr54** [TomorrowTodayLabs/NewtonVR#76]
I upgraded from NVR version July 29th, 2016 to currently the newest version Oct 24th, 2016 and noticed the NVR Canvas Input cursor is no longer aligned to where you are pointing on a canvas. It seems to be about 45 degrees off center to the right. 

This can be reproduced by opening NVR example scene, opening the door, and pointing at the canvas behind the door.

**Comment by noirb** [comment]
I can't seem to reproduce this with the latest version. If you attach an NVRExampleLaserPointer to your controller does the line drawn by the laser pointer look correct? For me, it travels straight out of the controller and the cursor drawn on the canvas is exactly where the LaserPointer hits it.

I did notice one thing, though: if you hold the grip buttons when not near an interactable object, so your controller becomes "physical", the point on the canvas still only tracks the original (now hidden) controller, so if the "physical" controller hits part of the door frame and rotates as a result, the cursor position is now inaccurate. (not sure if that would be considered a bug by the TomorrowTodayLabs folks or not, though, I'm still working on understanding the code)

**Comment by keithbradner** [comment]
This should have been fixed in 0.9.
