### ISSUE TITLE
Register/Deregister conflict with procedural items

### ISSUE THREAD

**Issue by SmartCarrion** [TomorrowTodayLabs/NewtonVR#77]
Hi,
I'm trying to procedurally construct items with a variety of box colliders.  When i try register the new colliders with the NVR Item, I get this error:

ArgumentException: An element with the same key already exists in the dictionary.
System.Collections.Generic.Dictionary`2[UnityEngine.Collider,NewtonVR.NVRInteractable].Add (UnityEngine.Collider key, NewtonVR.NVRInteractable value) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Collections.Generic/Dictionary.cs:404)
NewtonVR.NVRInteractables.Register (NewtonVR.NVRInteractable interactable, UnityEngine.Collider[] colliders) (at Assets/NewtonVR/NVRInteractables.cs:29)
ItemHelper.RegisterInteractable () (at Assets/Scripts/ItemHelper.cs:511)

This happens even if I call 'deregister' on the item right before I register it.  I even also tried calling this function i put in Interactables, passing it all the the new colliders:

```
public static void DeregisterColliders(Collider[] colliders)
        {
            foreach (Collider col in colliders)
            {
                ColliderMapping.Remove(col);
            }
        }
```

Any ideas? 

Thanks,
Ian

**Comment by keithbradner** [comment]
This will get fixed in the incoming abstraction update. There will be a method in InteractableItem called UpdateColliders which you can call whenever. Should be coming monday.

**Comment by SmartCarrion** [comment]
How's it going?  Any update on timing of the patch?  It's a been a month since anything new was added to the git.
