### ISSUE TITLE
Initial orientation of the NVRPlayer on Vive is not clear

### ISSUE THREAD

**Issue by pkarjala** [TomorrowTodayLabs/NewtonVR#82]
When your launch a new project and place the NVRPlayer object in the scene, it is not immediately clear what orientation the playable space will take on the object.  This is somewhat cumbersome, as you must launch the project once before you can tell what angle the playable space is going to take relative to the camera of the player.

I would recommend describing in the documentation what orientation the play space will take on the Vive depending on the initial orientation of the NVRPlayer camera direction; it currently appears that the camera direction will face the wide side of the player space rectangle.

Additionally, adding back in the playable space marker on the NVRPlayer object when using it in Unity 3D will help visually orient the developer.

**Comment by keithbradner** [comment]
Is forward in steamvr / oculus not forward of the nvrplayer object?

**Comment by pkarjala** [comment]
"forward" in this context is irrelevant.  What is important is that it is unclear what orientation the play space takes relative to the nvrplayer object, as the nvrplayer object does not render the PlayArea  included with the regular Steam VR library until _after_ the user has already booted the game and it is added to the scene.

**Comment by keithbradner** [comment]
Ah sorry, I misunderstood. I'll try and add something in like that. Not sure if Oculus has something similar to playarea like steamvr does so I'll try to give a kind of "default" if you don't have steamvr checked.

**Comment by keithbradner** [comment]
I've created a playarea representation as well as a player representation in the editor. Let me know if this fixes the issue :)

**Comment by pkarjala** [comment]
Thanks; I'll have access to the lab again on Monday for testing!

**Comment by keithbradner** [comment]
I've received a bunch of positive reactions from this change so I'm going to assume this is fixed and close.

**Comment by pkarjala** [comment]
Good to hear!  Wasn't able to get in the lab this week, but my vive arrives tomorrow, so will continue then.
