### ISSUE TITLE
Daydream support

### ISSUE THREAD

**Issue by omerfaruk** [TomorrowTodayLabs/NewtonVR#85]
Is it possible to add daydream support ?

**Comment by keithbradner** [comment]
We're definitely looking into it. Main blocker is we don't have one to test with.

**Comment by SmartCarrion** [comment]
I'd rather get a PS4 extension, but I'm hopeful i could roll my own if I
get to that stage.

**Comment by keithbradner** [comment]
We're also working on getting a PSVR. Strangely that seems easier.
