### ISSUE TITLE
Errors related to NVRPlayerEditorDownloader after first project start

### ISSUE THREAD

**Issue by bgr** [TomorrowTodayLabs/NewtonVR#88]
The following two errors appear when opening the project for the first time:

> A meta data file (.meta) exists but its asset 'Assets/NewtonVR/Editor/NVRPlayerEditorDownloader.cs' can't be found. When moving or deleting files outside of Unity, please ensure that the corresponding .meta file is moved or deleted along with it.

> Removing Assets/NewtonVR/Editor/NVRPlayerEditorDownloader.cs because the asset does not exist

**Comment by keithbradner** [comment]
Whoop, forgot to remove that. Thanks, will fix soon.

**Comment by keithbradner** [comment]
Thanks again, removed.
