### ISSUE TITLE
Doesn't work in Unity 5.4.3f1

### ISSUE THREAD

**Issue by bgr** [TomorrowTodayLabs/NewtonVR#89]
The following errors show up when running the example scene in Unity 5.4.3f1 with HTC Vive.
Note that CurrentIntegration error appears twice.
Removing Oculus, OpenVR or both from Player settings Virtual Reality SDKs or disabling VR completely doesn't help.

> OpenVR initialized!

> [NewtonVR] Version : 0.97. Found VRDevice: Vive MV. 

> [NewtonVR] Critical Error: Oculus / SteamVR not setup properly or no headset found.
>> UnityEngine.Debug:LogError(Object)
>> NewtonVR.NVRPlayer:SetupIntegration(Boolean) (at Assets/NewtonVR/NVRPlayer.cs:201)
>> NewtonVR.NVRPlayer:Awake() (at Assets/NewtonVR/NVRPlayer.cs:157)

> [NewtonVR] Critical Error: NVRPlayer.CurrentIntegration not setup.
>> UnityEngine.Debug:LogError(Object)
>> NewtonVR.NVRHand:PreInitialize(NVRPlayer) (at Assets/NewtonVR/NVRHand.cs:174)
>> NewtonVR.NVRPlayer:Awake() (at Assets/NewtonVR/NVRPlayer.cs:165)

> [NewtonVR] Critical Error: NVRPlayer.CurrentIntegration not setup.
>> UnityEngine.Debug:LogError(Object)
>> NewtonVR.NVRHand:PreInitialize(NVRPlayer) (at Assets/NewtonVR/NVRHand.cs:174)
>> NewtonVR.NVRPlayer:Awake() (at Assets/NewtonVR/NVRPlayer.cs:165)

> NullReferenceException: Object reference not set to an instance of an object
>> NewtonVR.NVRPlayer.Awake () (at Assets/NewtonVR/NVRPlayer.cs:169)

**Comment by keithbradner** [comment]
Whoops! Thanks for reporting. We'll get this fixed asap

**Comment by keithbradner** [comment]
Seems like the master branch got out of sync with development for some reason. Can you try version 0.981 (committed a few minutes ago) and tell me if you have the same issues?

**Comment by bgr** [comment]
Yes, commit 4f94d939 (version 0.985) gives the exact same errors.

I also tried running Unity as administrator, doesn't help. Trying on Windows 10 Anniversary Edition.

**Comment by keithbradner** [comment]
In your NVRPlayer do you have Enable SteamVR checked? Maybe I should make that error more descriptive

**Comment by bgr** [comment]
Yeah, it might be good to make the error more descriptive. I didn't have it checked, thanks. Now it works and there are no errors, although there is this message:

> [NewtonVR] Version : 0.987. Found VRDevice: Vive MV. Using SteamVR SDKDid not find supported VR device. Or no integrations enabled.

**Comment by keithbradner** [comment]
Thank! And sorry about that. Clear setup instructions and error messages are definitely important. I'll try and fix that log error too
