### ISSUE TITLE
Consider using SendMessage for NVRInteractableItem

### ISSUE THREAD

**Issue by MattRix** [TomorrowTodayLabs/NewtonVR#9]
Just thought I'd suggest that you may want to use [SendMessage ](http://docs.unity3d.com/ScriptReference/Component.SendMessage.html) for stuff like UseButtonUp and UseButtonDown. It will fit the Unity-style approach a bit better, rather than requiring people to extend the NVRInteractableItem directly.

**Comment by keithbradner** [comment]
I'm not really a big fan of SendMessage. I find it leads to hard to debug code and unreliable states. Extending the class requires you to be more purposeful in your programming :)

**Comment by MattRix** [comment]
Heh, I don't agree with that, but it's your project. Thanks for considering it anyway! :)
