### ISSUE TITLE
Bug in NVRCollisionSoundProviderUnity. Does not play all available clips

### ISSUE THREAD

**Issue by 14422** [TomorrowTodayLabs/NewtonVR#93]
We are using a couple months old version of NewtonVR in our game and I noticed there's still one bug that exists nowadays. In NVRCollisionSoundProviderUnity in the GetClip() method, it gets a random clip but the max range in Random.Range has -1 so it never get's the last clips in the folder. For example with 6 clips, only 5 are used randomly.

The code part looks like this:
int index = Random.Range(0, Clips[material].Count - 1);

and if the -1 is removed from the end, all clips are used.

By the way, it's my first time ever contributing to anything on GitHub so I'm sorry if this should be a pull request or such.

**Comment by keithbradner** [comment]
Ah, thanks! Nice catch! Put in the fix just now.
