### ISSUE TITLE
UI canvas interaction not working with Unity 5.5

### ISSUE THREAD

**Issue by Andze** [TomorrowTodayLabs/NewtonVR#94]
I have just updated to the latest version of Unity and Newton 1.0 to play around with the new features and discovered that the UI interaction doesn't work in Unity 5.5, it works correctly in 5.4.3.

**Comment by keithbradner** [comment]
Thanks for the bug report. It seems like unity decided to stop executing BaseInputMethod.Process. I've gone ahead and changed it to Update temporarily to fix the issue for NewtonVR.
