### ISSUE TITLE
Multiple button Item interactions?

### ISSUE THREAD

**Issue by Theodorehip** [TomorrowTodayLabs/NewtonVR#99]
Hi team,
First of all, great job, i love this plugin so much. Saved me a ton of headache in working on my project.
I'm having one issue though.
I have an object that can be picked up with the Grip buttons, and interacted on with the Trigger. But i also want the touchpad to trigger another script on the object. 
I've been combing through your code, and i cant find a simple way to do that on my own while still within your system.
Can you either point me in the right direction, or point out how i'm being an idiot. 
Thanks.

**Comment by keithbradner** [comment]
Thanks! NVRExampleGrower.cs has a nice example of that. It's in the example scene. Basically here's what you want:

```
public class NVRExampleGrower : NVRInteractableItem
{
    public override void InteractingUpdate (NVRHand hand)
    {
        base.InteractingUpdate (hand);

	if (hand.Inputs[NVRButtons.Touchpad].PressUp == true)
        {
	    //do stuff
	}
    }
}
```

**Comment by Theodorehip** [comment]
@zite Thank you so much, you got back to this so quickly. I dont know what timezone you're in, but i posted that at 1 am, so your correspondence is incredible for me. Thank You again.
